CREATE TYPE StanPracyStacjiPogodowej_enum AS ENUM (
    'letni',
    'zimowy'
    );

CREATE TYPE StanCzujnika_enum AS ENUM (
    'dobry',
    'bardzo_dobry',
    'normalny',
    'zly'
    );

CREATE TYPE RolaUzytkownika_enum AS ENUM (
    'administrator',
    'pracownik_rolny',
    'producent_rolny',
    'instalator'
    );

CREATE TABLE stacja_pogodowa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wymiary_id integer,
    waga_stacji float,
    gwarancja_id integer,
    stan_pracy StanPracyStacjiPogodowej_enum,
    wlasciciel_id integer
);

CREATE TABLE wymiary (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    szerokosc integer,
    wysokosc integer,
    dlugosc integer
);

CREATE TABLE gwarancja (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash_godnosci character varying(255),
    instrukcja_uzytkownika character varying(1000)
);

CREATE TABLE pomiar_czujnika (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    czas_odczytu date,
    stan_czujnika StanCzujnika_enum,
    stacja_pogodowa_id integer
);

CREATE TABLE pomiar_czujnika_zew (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cisnienie_atmosferyczne float,
    opady_deszczu float,
    jakosc_powietrza float,
    predkosc_wiatru float,
    promieniowanie_sloneczne float,
    temperatura_odczuwalna float,
    temperatura_zewnetrzna float,
    wilgotnosc_zewnetrzna float,
    fars float,
    uvi float
);

CREATE TABLE pomiar_czujnika_wew (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maksymalny_zasieg integer,
    temperatura_wewnetrzna float,
    wilgotnosc_wewnetrzna float
);

CREATE TABLE uzytkownik (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at date,
    login character varying(255),
    rola_uzytkownika RolaUzytkownika_enum
);

ALTER TABLE stacja_pogodowa
    ADD FOREIGN KEY (wymiary_id) REFERENCES wymiary(id);


ALTER TABLE stacja_pogodowa
    ADD FOREIGN KEY (gwarancja_id) REFERENCES gwarancja(id);


ALTER TABLE stacja_pogodowa
    ADD FOREIGN KEY (wlasciciel_id) REFERENCES uzytkownik(id);


ALTER TABLE pomiar_czujnika
    ADD FOREIGN KEY (stacja_pogodowa_id) REFERENCES stacja_pogodowa(id);


ALTER TABLE pomiar_czujnika_wew
    ADD FOREIGN KEY (id) REFERENCES pomiar_czujnika(id);


ALTER TABLE pomiar_czujnika_zew
    ADD FOREIGN KEY (id) REFERENCES pomiar_czujnika(id);

