/*
 * API back-endu aplikacji PoGOODa
 * Back-end aplikacji PoGOODa do użycia na projekcie z przedmiotu \"Projektowanie oprogramowania\". API zgodne z OAS v3.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DanePogodoweDto} from './DanePogodoweDto';

/**
 * The PrognozaPogodyDto model module.
 * @module model/PrognozaPogodyDto
 * @version 1.0.0
 */
export class PrognozaPogodyDto {
  /**
   * Constructs a new <code>PrognozaPogodyDto</code>.
   * @alias module:model/PrognozaPogodyDto
   * @class
   * @param miejsce {String} 
   * @param prognozy {Array.<module:model/DanePogodoweDto>} 
   */
  constructor(miejsce, prognozy) {
    this.miejsce = miejsce;
    this.prognozy = prognozy;
  }

  /**
   * Constructs a <code>PrognozaPogodyDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrognozaPogodyDto} obj Optional instance to populate.
   * @return {module:model/PrognozaPogodyDto} The populated <code>PrognozaPogodyDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrognozaPogodyDto();
      if (data.hasOwnProperty('miejsce'))
        obj.miejsce = ApiClient.convertToType(data['miejsce'], 'String');
      if (data.hasOwnProperty('prognozy'))
        obj.prognozy = ApiClient.convertToType(data['prognozy'], [DanePogodoweDto]);
    }
    return obj;
  }
}

/**
 * @member {String} miejsce
 */
PrognozaPogodyDto.prototype.miejsce = undefined;

/**
 * @member {Array.<module:model/DanePogodoweDto>} prognozy
 */
PrognozaPogodyDto.prototype.prognozy = undefined;

